#!/usr/bin/env bash
# Paired all-reduce comparison: mainarch (raw KFD/AQL, no ROCm) vs RCCL.
#
# Runs both stacks over the same 8-GPU power-of-two ladder and writes a merged
# delta table to baseline/allreduce-comparison.txt. RCCL runs in a sibling
# container built from upstream rccl-tests; mainarch runs natively from this
# workspace.
#
# You must supply the RCCL image yourself. There is no public image with
# rccl-tests prebuilt. See baseline/README.md for how to build one:
#
#   MAINARCH_RCCL_IMAGE=<your-rccl-tests-image> bench/compare-allreduce.sh
#
# RCCL_ARGS picks the RCCL process/thread layout. Default is `-t 8 -g 1`
# (8 threads, one GPU each), which is RCCL's FASTEST configuration and
# therefore the honest comparator. `-g 8` (one thread driving 8 GPUs)
# serializes RCCL's launch path and makes mainarch look better than it is;
# use it only if you are explicitly measuring the single-threaded case, and
# say so wherever you quote the result.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
OUT="${1:-$REPO/baseline/allreduce-comparison.txt}"
IMAGE="${MAINARCH_RCCL_IMAGE:-}"
RCCL_ARGS="${RCCL_ARGS:--t 8 -g 1}"
MINB="${MINBYTES:-1024}"
MAXB="${MAXBYTES:-67108864}"

if [ -z "$IMAGE" ]; then
  echo "MAINARCH_RCCL_IMAGE is unset." >&2
  echo "Point it at a container image with upstream rccl-tests built inside." >&2
  echo "See baseline/README.md." >&2
  exit 2
fi

mkdir -p "$(dirname "$OUT")"
mh="$(mktemp)"
rh="$(mktemp)"
trap 'rm -f "$mh" "$rh"' EXIT

echo ">> mainarch all-reduce (native, raw KFD/AQL, no ROCm)"
cargo run -q --release -p mainarch-cli -- gpu-allreduce-bench \
  --min-bytes "$MINB" --max-bytes "$MAXB" --iters 50 --warmup 10 \
  2>/dev/null | grep -E "^ +[0-9]+ " > "$mh" || true

echo ">> RCCL all_reduce_perf (sibling container)"
docker run --rm --device /dev/kfd --device /dev/dri \
  --group-add video --group-add render --security-opt seccomp=unconfined \
  --ipc=host "$IMAGE" -b "$MINB" -e "$MAXB" -f 2 $RCCL_ARGS \
  2>/dev/null | grep -E "^ +[0-9]+ +[0-9]+ +float" > "$rh" || true

{
  echo "# all-reduce: mainarch (raw KFD/AQL, no ROCm) vs RCCL, 8x gfx950"
  echo "# generated by bench/compare-allreduce.sh"
  echo "# busbw convention: algbw * 2*(R-1)/R; lower time is better"
  echo "# RCCL invocation: all_reduce_perf -b $MINB -e $MAXB -f 2 $RCCL_ARGS"
  echo "#"
  printf "%14s  %16s  %14s  %14s  %10s\n" \
    "size(B)" "mainarch_us" "rccl_us" "mainarch_busbw" "rccl_busbw"
  printf "%14s  %16s  %14s  %14s  %10s\n" \
    "-------" "-----------" "-------" "--------------" "----------"
  # mainarch: cols = size count time algbw busbw
  # rccl:     cols = size count type redop root time algbw busbw nwrong (in-place repeats)
  while read -r size _ mtime _ mbus; do
    rline="$(awk -v s="$size" '$1==s {print; exit}' "$rh")"
    rtime="$(echo "$rline" | awk '{print $6}')"
    rbus="$(echo "$rline" | awk '{print $8}')"
    printf "%14s  %16s  %14s  %14s  %10s\n" \
      "$size" "$mtime" "${rtime:-NA}" "$mbus" "${rbus:-NA}"
  done < "$mh"
} | tee "$OUT"

echo
echo "wrote $OUT"
